name: EA0326GMP
on: push
env:
  SSH_ACTIONS: true
jobs:
  build-firmware:
    runs-on: ubuntu-20.04
    steps:
    - name: set-env
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang clangd cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev libssl-dev libtool lld lldb lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
    - name: set-repo
      run: |
        git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git
        cd immortalwrt-mt798x
        curl -s https://github.com/hanwckf/immortalwrt-mt798x/commit/ad31ed01841e2af081803b850974c8c9367c7a27.patch -o ea0326gmp.patch
        git apply ea0326gmp.patch
    - name: set-feeds
      run: |
        cd immortalwrt-mt798x
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: build-config
      run: |
        cd immortalwrt-mt798x
        cp -f defconfig/mt7981-ax3000.config .config
        make menuconfig
    - name: build
      run: |
        cd immortalwrt-mt798x
        make -j$(nproc)
    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: immortalwrt-mt798x-built
        path: immortalwrt-mt798x/bin
